#Turn PlantNerfer off.
disable-plugin: false


##############
#Biome Groups#
##############

biome-group-list:
#  TestGroup:
#    - "PLAINS"
#    - "SAVANNA"
#  second-group:
#    - "FOREST"


#############
#Nerf Plants#
#############

#Note: 'dark' light levels are between and including 0 and 7.
#Note 2: different plants have different numbers of growth stages, which means the same growth rate can affect some plants more than others.
#Note 3: for a successful bone meal fertilization growth, the plant must go through bone meal rate, growth rate, and vanilla bone meal chance checks.
#Nore 4: to see the default values, visit the documentation page: https://github.com/lichenaut/PlantNerfer

#Example:
#oak-sapling:
#  can-place: true
#  growth-rate: 25
#  death-rate: 10
#  growth-rate-dark: 15
#  death-rate-dark: 20
#  bone-meal-success-rate: 25
#  bone-meal-success-rate-dark: 10
#  min-light: 9
#  max-light: 15
#  place-and-bone-meal-ignores-min-light-at-night: true
#  needs-sky: false
#  min-y: 0
#  max-y: 200
#  restrict-to-worlds:
#    - "world"
#    - "world_nether"
#  biome-groups:
#    second-group:
#      growth-rate: 100
#      bone-meal-success-rate: 100
#      bone-meal-success-rate-dark: 100
#      restrict-to-worlds:
#        - "world"
#      max-y: 255
#      needs-sky: false
#    TestGroup:
#      can-place: false
#      restrict-to-worlds:
#        - "world_nether"


oak-sapling:
dark-oak-sapling:
spruce-sapling:
birch-sapling:
jungle-sapling:
acacia-sapling:
bamboo-sapling:
bamboo:
cherry-sapling:
mangrove-propagule:
mangrove-leaves:
sugar-cane:
sea-pickle:
kelp:
seagrass:
grass:
tall-grass:
grass-block:
fern:
large-fern:
vine:
twisting-vines:
weeping-vines:
lily-pad:
moss-carpet:
moss-block:
sweet-berry-bush:
melon-stem:
pumpkin-stem:
carrot:
potato:
beetroot:
wheat:
cactus:
cocoa:
brown-mushroom:
red-mushroom:
torchflower-crop:
pitcher-crop:
nether-wart:
crimson-fungus:
warped-fungus:
big-dripleaf:
small-dripleaf:
rooted-dirt:
chorus-plant:
azalea:
flowering-azalea:
sunflower:
lilac:
rose-bush:
peony:
dandelion:
poppy:
blue-orchid:
allium:
azure-bluet:
red-tulip:
orange-tulip:
white-tulip:
pink-tulip:
oxeye-daisy:
cornflower:
lily-of-the-valley:
pink-petals:


###############
#Miscellaneous#
###############

#If empty, PlantNerfer will affect all worlds.
  #To disable the plugin completely, scroll to the top of this file and set disable-plugin to true.
restrict-plugin-to-worlds:
#  - "world"
#  - "world_nether"
#  - "world_the_end"

#Toggle whether everyone can right-click a plant and see its bone meal success rate.
  #Individual permission: plantnerfer.bonemealrate
global-bone-meal-rate-reporting: false
  #Permission to disable individual bone meal rate reporting when the global setting is true: plantnerfer.bonemealrate.disabled