name: PlantNerfer
version: "${project.version}"
main: com.lichenaut.plantnerfer.Main
api-version: "1.20"
author: lichenaut
description: PlantNerfer allows for very configurable plant behavior.
commands:
  plantnerfer:
    description: "Base command for PlantNerfer plugin."
    aliases: [pn]
