name: PlantNerfer
version: '${project.version}'
main: com.lichenaut.plantnerfer.PlantNerfer
api-version: '1.14'
author: lichenaut
description:
  PlantNerfer allows for very configurable plant behavior, versions 1.14+.
commands:
  plantnerfer:
    description: "Base command for PlantNerfer plugin."
    aliases: [pn]